NET_projekt/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace NET_projekt.Models
{
    public class User
    {
        //-----------------------------------------------------------------
        [Key]
        public int UserId { get; set; }
        //-----------------------------------------------------------------
        [Required(ErrorMessage = "Te pole jest wymagane!")]
        [DisplayName("Nazwa użytkownika")]
        [StringLength(50,  MinimumLength = 4, ErrorMessage = "Nazwa użytkownika musi zawierać od 4 do 50 liter")]
        [RegularExpression(@"[A-Za-z0-9]*", ErrorMessage = "Nazwa użytkownika może składać się wyłącznie z cyfr i liter")]
        public string Nickname { get; set; }
        //-----------------------------------------------------------------
        [Required(ErrorMessage = "Te pole jest wymagane!")]
        [DisplayName("Adres e-mail")]
        [EmailAddress(ErrorMessage = "Proszę podać poprawny adres e-mail")]
        public string EmailAddress { get; set; }
        //-----------------------------------------------------------------
        [Required]
        [DisplayName("Hasło")]
        [DataType(DataType.Password)]
        [MinLength(8, ErrorMessage = "Hasło musi składać się z minimum 8 znaków")]
        public string Password { get; set; }
        //-----------------------------------------------------------------
        [Required]
        public string Salt { get; set; }
        //-----------------------------------------------------------------
        [Required]
        [DisplayName("Status premium")]
        public bool PremiumStatus { get; set; } = false;
        //-----------------------------------------------------------------
        public virtual ICollection<Dataset> Datasets { get; set; }
        //-----------------------------------------------------------------
        /*[NotMapped]
        [Required]
        [System.ComponentModel.DataAnnotations.Compare("Password")]
        public string ConfirmPassword { get; set; }*/
        //-----------------------------------------------------------------
    }
}

NET_projekt/Controllers/DatasetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NET_projekt.Models;
using System.Text;
using System.Security.Cryptography;
using System.Web.UI.WebControls;
using Microsoft.VisualBasic.FileIO;
using Newtonsoft.Json;
using System.Net;
using System.IO;
using System.Data;

namespace NET_projekt.Controllers
{
    public class DatasetController : Controller
    {
        private DefaultContext db = new DefaultContext();

        //HTTP: GET------------------------------------------------------------------
        public ActionResult AddDataset(int? UserId)
        {
            if (UserId == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            User User = db.Users.Find(UserId);
            if (User == null) return HttpNotFound();
            return View(new Dataset { ConcreteUser = User });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddDataset(HttpPostedFileBase file, string DatasetName, string DatasetColumnsInfo, int DatasetHzFrequency)
        {
            if (ModelState.IsValid) //Model-binding validation - odwołuje się do adnotacji w Modelach
            {
                { //poprawność DatasetColumnsInfo
                    string[] lines = DatasetColumnsInfo.Split(new char[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
                    DatasetColumnsInfo = "";
                    foreach (string line in lines)
                    {
                        string[] name_numbers = line.Split(new char[] { ':' });
                        if (name_numbers.Length != 2 || name_numbers[0].Length == 0)
                        {
                            ViewBag.dataseterror = "Przykładowa prawidłowa postać: ECG:1,2,3 EMG:4,5 AAA:6";
                            return View();
                        }
                        string[] potentialdigits = name_numbers[1].Split(new char[] { ',' });
                        foreach (var potentialdigit in potentialdigits)
                        {
                            if (potentialdigit.Length == 0)
                            {
                                ViewBag.dataseterror = "Przykładowa prawidłowa postać: ECG:1,2,3 EMG:4,5 AAA:6";
                                return View();
                            }
                            int number;
                            bool success = Int32.TryParse(potentialdigit, out number);
                            if (!success)
                            {
                                ViewBag.dataseterror = "Przykładowa prawidłowa postać: ECG:1,2,3 EMG:4,5 AAA:6";
                                return View();
                            }
                        }
                        DatasetColumnsInfo += line + " ";
                    }
                    DatasetColumnsInfo = DatasetColumnsInfo.Substring(0, DatasetColumnsInfo.Length - 1);
                }
                if (file != null && file.ContentLength > 0)
                {
                    string extension = Path.GetExtension(file.FileName);
                    if (extension == ".csv")
                    {
                        ViewBag.Message = "Wybrano odpowiedni plik";
                        //string path = Path.Combine(Server.MapPath("~"), Path.GetFileName(file.FileName));
                        string path = System.IO.Path.Combine(System.IO.Path.GetDirectoryName(Path.GetDirectoryName
                            (AppDomain.CurrentDomain.BaseDirectory)), @"Dane\\" + DatasetName + Session["Nickname"].ToString() + ".csv");
                        file.SaveAs(path);
                        Dataset NewDataSet = new Dataset();
                        NewDataSet.DatasetName = DatasetName;
                        NewDataSet.DatasetColumnsInfo = DatasetColumnsInfo;
                        NewDataSet.DatasetHzFrequency = DatasetHzFrequency;
                        NewDataSet.ConcreteUser = db.Users.Find(Convert.ToInt32(Session["UserId"]));
                        NewDataSet.Reference = path.ToString();
                        NewDataSet.DateAdded = DateTime.Now;
                        db.Datasets.Add(NewDataSet);
                        db.SaveChanges();
                        return RedirectToAction("Index", "User");
                    }
                    else ViewBag.Message = "Należy wybrać plik '.csv'";
                }
                else ViewBag.Message = "Nie wybrano konkretnego pliku.";
                return View();
            }
            return View();
        }
        //HTTP: GET------------------------------------------------------------------
        public ActionResult DeleteDataset(int? Id)
        {
            if (Id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Dataset Dts = db.Datasets.Find(Id);
            if (Dts == null) return HttpNotFound();
            return View(Dts);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteDataset(int Id)
        {
            Dataset Dts = db.Datasets.Find(Id);
            //Usuwanie z folderu
            string path = Path.Combine(Path.GetDirectoryName(Path.GetDirectoryName
                (AppDomain.CurrentDomain.BaseDirectory)), @"Dane\\" + Dts.DatasetName + Session["Nickname"].ToString() + ".csv");
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }
            //Usuwanie z DB
            db.Datasets.Remove(Dts);
            db.SaveChanges();
            return RedirectToAction("Index", "User");
        }

        //HTTP: GET------------------------------------------------------------------
        public ActionResult Graph(int? Id, int time = 0, bool previousData = false)
        {
            if (time < 0) time = 0;
            if (previousData == true) Session["StopForward"] = "false";
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dataset Dts = db.Datasets.Find(Id); //Wyszukuje odpowiedni dataset w DB
            if (Dts == null) return HttpNotFound();
            StreamReader Sr = new StreamReader(Dts.Reference); //Chwyta się odp. csv'ki
            List<String> Lines = new List<String>(); //Pusta lista na przekazane linie

            if (Convert.ToString(Session["StopForward"]) == "true") time = time - 30;
            for (int i = 0; i <= time * Dts.DatasetHzFrequency; i++) Sr.ReadLine();
            for (int i = 0; i < 30 * Dts.DatasetHzFrequency; i++) //Doczytuje tyle linii, by było na 30 sekund
            {
                if (Sr.EndOfStream == true)
                {
                    Session["StopForward"] = "true";
                    break;
                }
                string s = Sr.ReadLine();
                Lines.Add(s);
            }
            ViewBag.DataLines = JsonConvert.SerializeObject(Lines); //Wstawia linie do vievbaga by łatwo je uzyskać w widoku
            GraphModel Gm = new GraphModel { Dataset = Dts, Time = time };
            Sr.Close();
            return View(Gm);
        }


    }
}

NET_projekt/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NET_projekt.Models;
using System.Text;
using System.Security.Cryptography;
using System.Web.UI.WebControls;
using Microsoft.VisualBasic.FileIO;
using Newtonsoft.Json;
using System.Net;
using System.IO;
using System.Data;

namespace NET_projekt.Controllers
{
    public class UserController : Controller
    {
        private DefaultContext db = new DefaultContext();
        //HTTP: GET------------------------------------------------------------------
        public ActionResult Index()
        {
            if (Session["UserId"] != null)
            {
                string actsession = Session["Nickname"].ToString();
                User actuser = db.Users.Where(u => u.Nickname.Equals(actsession)).FirstOrDefault();
                return View(actuser);
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }
        //HTTP: GET------------------------------------------------------------------
        public ActionResult Register()
        {
            if (Session["UserId"] != null)
            {
                return RedirectToAction("Index", "User");
            }
            return View(new User());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(string nickname, string emailaddress, string password)
        {
            if (ModelState.IsValid)
            {
                var ExistingUsername = db.Users.Where(u => u.Nickname.Equals(nickname)).ToList();
                if (ExistingUsername.Count() == 0)
                {
                    var tuple_p = hash(password);
                    User NewUser = new User
                    {

                        Nickname = nickname,
                        EmailAddress = emailaddress,
                        Password = tuple_p.Item2,
                        Salt = tuple_p.Item1

                    };
                    db.Configuration.ValidateOnSaveEnabled = false;
                    db.Users.Add(NewUser);
                    db.SaveChanges();
                    return RedirectToAction("Index", "User");
                }
                else
                {
                    ViewBag.error = "Ta nazwa użytkownika jest już zajęta!";
                    return View(new User());
                }
            }
            return View();
        }

        //HTTP: GET------------------------------------------------------------------
        public ActionResult Login()
        {
            if (Session["UserId"] != null)
            {
                return RedirectToAction("Index", "User");
            }
            return View(new User());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string nickname, string password)
        {

            if (ModelState.IsValid)
            {

                var PossibleUser = db.Users.Where(u => u.Nickname.Equals(nickname)).ToList();
                if (PossibleUser.Count() > 0)
                {
                    User u = PossibleUser.FirstOrDefault();
                    string salted_password = password + u.Salt;
                    string hash_password = only_hash(salted_password);
                    if (u.Password.Equals(hash_password))
                    {
                        Session["UserId"] = u.UserId;
                        Session["Nickname"] = u.Nickname;
                        Session["EmailAddress"] = u.EmailAddress;
                        Session["PremiumStatus"] = u.PremiumStatus;
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.error = "Podano nieprawidłowy login lub hasło";
                        //return RedirectToAction("Login");
                        return View(new User());
                    }
                }
                else
                {
                    ViewBag.error = "Podano nieprawidłowy login lub hasło";
                    //return RedirectToAction("Login");
                    return View(new User());
                }
            }
            return View(new User());
        }
        public (string, string) hash(string password)
        {
            //salt
            byte[] salt;
            new RNGCryptoServiceProvider().GetBytes(salt = new byte[32]);
            string salt_string = Convert.ToBase64String(salt);
            string salted_password = password + salt_string;

            // hash
            HashAlgorithm hasgAlg = new SHA256CryptoServiceProvider();
            byte[] Value = System.Text.Encoding.UTF8.GetBytes(salted_password);
            byte[] Hash = hasgAlg.ComputeHash(Value);
            string hashed_password = Convert.ToBase64String(Hash);
            return (salt_string, hashed_password);
        }
        public string only_hash(string salted_password)
        {
            HashAlgorithm hasgAlg = new SHA256CryptoServiceProvider();
            byte[] Value = System.Text.Encoding.UTF8.GetBytes(salted_password);
            byte[] Hash = hasgAlg.ComputeHash(Value);
            string hashed_password = Convert.ToBase64String(Hash);
            return hashed_password;
        }

        //HTTP: GET------------------------------------------------------------------
        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Login", "User");
        }
    }
}

NET_projekt/Views/User/Index.cshtml
@model NET_projekt.Models.User

@{
    ViewBag.Title = "Index";
}
<div class="row justify-content-md-end">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                Witaj
            </div>
            <div class="card-body">
                @if (Session["UserId"] != null)
                {
                    <p>Nazwa: @Session["Nickname"].ToString()</p>
                    <p>E-mail: @Session["EmailAddress"].ToString()</p>
                    <a href="@Url.Action("Logout","User")" class="btn btn-dark">Wyloguj się</a>
                }
            </div>
        </div>
    </div>
</div>

<div style="margin-top: 50px;"><h1 class="row justify-content-md-center">Dostępne dataset'y:</h1></div>
<table class="table">
    <caption>Dataset'y użytkownika @Session["Nickname"].ToString()</caption>
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nazwa dataset'u</th>
            <th scope="col">Data dodania</th>
            <th scope="col">Typy danych</th>
            <th scope="col">Częstotliwość [Hz]</th>
            <th scope="col" class="text-center">Podgląd</th>
        </tr>
    </thead>
    <tbody>
        @{
            for (int i = 0; i < Model.Datasets.Count; i++)
            {
                <tr>
                    <th scope="row">@i</th>
                    <td>@Html.DisplayFor(modelItem => Model.Datasets.ElementAt(i).DatasetName)</td>
                    <td>@Html.DisplayFor(modelItem => Model.Datasets.ElementAt(i).DateAdded)</td>
                    <td>@{
                        string types = "";
                        foreach(var item in Model.Datasets.ElementAt(i).DatasetColumnsInfo.Split(' '))
                        {
                            types += item.Split(':')[0]+" ";
                        }
                        @types
                        }</td>
                    <td>@Html.DisplayFor(modelItem => (Model.Datasets.ElementAt(i).DatasetHzFrequency))</td>
                    <td class="text-center">
                        <input type="button" value="Przejrzyj" class="btn btn-success" onclick="location.href='@Url.Action("Graph", "Dataset", new { id = Model.Datasets.ElementAt(i).Id })'" />
                        <input type="button" value="Usuń" class="btn btn-danger" onclick="location.href='@Url.Action("DeleteDataset", "Dataset", new { id = Model.Datasets.ElementAt(i).Id })'" />
                    </td>
                </tr>
            }
        }
    <tr>
        <td colspan="5"></td>
        <td class="text-center"><input type="button" value="Dodaj nowy" class="btn btn-primary" onclick="location.href='@Url.Action("AddDataset", "Dataset", new { UserId = Model.UserId  })'"/></td>
    </tr>
    </tbody>
</table>

NET_projekt/Views/User/Login.cshtml
@model NET_projekt.Models.User

@{
    ViewBag.Title = "Login";
}

<div class="row justify-content-md-center">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Logowanie</div>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Login", "User", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                <div class="form-group">
                    @Html.LabelFor(m => m.Nickname)
                    @Html.TextBoxFor(m => m.Nickname, "", new { @class = "form-control", @placeholder = "Nazwa użytkownika" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password)
                    @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Hasło" })
                    @if (ViewBag.error != null)
                    {
                        <span class="badge badge-danger">@ViewBag.error</span>
                    }
                </div>
                    <div class="form-group">
                        <input type="submit" name="submit" class="btn btn-primary" value="Login" />
                    </div>
                }
                @Html.ActionLink("Nie masz konta? Zarejestruj się.", "Register", "User")
            </div>
        </div>
    </div>
</div>

NET_projekt/Views/User/Register.cshtml
@model NET_projekt.Models.User

@{
    ViewBag.Title = "Register";
}

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<link href="~/Content/Site.css" rel="stylesheet" />

<div class="row justify-content-md-center">
    <div class="col-md-5">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Rejestracja</div>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Register", "User", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        @Html.LabelFor(m => m.Nickname)
                        @Html.TextBoxFor(m => m.Nickname, "", new { @class = "form-control", @placeholder = "Nazwa użytkownika" })
                        @Html.ValidationMessageFor(m => m.Nickname, "", new { @class = "badge badge-danger" })
                        @if (ViewBag.error != null)
                        {
                            <span class="badge badge-danger">@ViewBag.error</span>
                        }
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.EmailAddress)
                        @Html.TextBoxFor(m => m.EmailAddress, "", new { @class = "form-control", @placeholder = "Adres e-mail" })
                        @Html.ValidationMessageFor(m => m.EmailAddress, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Password)
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Hasło" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        <input type="submit" name="submit" class="btn btn-danger" value="Rejestracja" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>