NET_projekt/Controllers/ExamplePlotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NET_projekt.Models;
using System.Text;
using System.Security.Cryptography;
using System.Web.UI.WebControls;
using Microsoft.VisualBasic.FileIO;
using Newtonsoft.Json;
using System.Net;
using System.IO;
using System.Data;
namespace NET_projekt.Controllers
{
    public class ExamplePlotController : Controller
    {
        public ActionResult Example_plot(bool ecg, bool emg, int choose_Hz, int time)
        {
            string path = @"../../Dane";
            List<DataPoint> ECG = new List<DataPoint>();
            List<DataPoint> EMG = new List<DataPoint>();

            double a = 0;
            switch (choose_Hz)
            {
                case 10:
                    path = AppDomain.CurrentDomain.BaseDirectory;
                    path = Path.Combine(Path.GetDirectoryName(Path.GetDirectoryName(path)), @"Dane\ecg_emg_10Hz_30s.csv");
                    a = 0.1;
                    break;
                case 100:
                    path = AppDomain.CurrentDomain.BaseDirectory;
                    path = Path.Combine(Path.GetDirectoryName(Path.GetDirectoryName(path)), @"Dane\ecg_emg_100Hz_30s.csv");
                    a = 0.01;
                    break;

                case 250:
                    path = AppDomain.CurrentDomain.BaseDirectory;
                    path = Path.Combine(Path.GetDirectoryName(Path.GetDirectoryName(path)), @"Dane\ecg_emg_250Hz_30s.csv");
                    a = 0.004;
                    break;
                defult:
                    break;
            }
            using (TextFieldParser csvParser = new TextFieldParser(path))
            {
                csvParser.CommentTokens = new string[] { "#" };
                csvParser.SetDelimiters(new string[] { "," });
                csvParser.HasFieldsEnclosedInQuotes = true;
                csvParser.ReadLine();
                double ile = 0;
                while (!csvParser.EndOfData && ile <= time)
                {
                    string[] fields = csvParser.ReadFields();

                    ECG.Add(new DataPoint(ile, double.Parse(fields[1], System.Globalization.CultureInfo.InvariantCulture)));

                    EMG.Add(new DataPoint(ile, double.Parse(fields[2], System.Globalization.CultureInfo.InvariantCulture)));
                    ile += a;
                }
            }
            if (ecg == true)
            {
                ViewBag.DataPoints = JsonConvert.SerializeObject(ECG);
                ViewBag.MyMessage = "ECG";
            }
            if (emg == true)
            {
                ViewBag.DataPoints = JsonConvert.SerializeObject(EMG);
                ViewBag.MyMessage = "EMG";
            }

            return View();
        }



        public ActionResult User_plot(List<String> data_list, int choose_Hz, int start_time, int wyw)
        {

            Session["choose_Hz"] = choose_Hz;
            Session["start_time"] = start_time;
            string[] fields_name = new string[8];
            int end_time = start_time + 30;
            List<List<DataPoint>> user_data = new List<List<DataPoint>>();
            var path = (string)Session["path"];
            var fields = (List<String>)Session["fields"];
            using (TextFieldParser csvParser = new TextFieldParser(path))
            {
                csvParser.CommentTokens = new string[] { "#" };
                csvParser.SetDelimiters(new string[] { "," });
                csvParser.HasFieldsEnclosedInQuotes = true;
                csvParser.ReadLine();
                double skok = 1 / Convert.ToDouble(choose_Hz);
                for (int i = 1; i < fields.Count; i++)
                {

                    double ile = start_time;
                    List<DataPoint> pom = new List<DataPoint>();
                    user_data.Add(pom);
                    double count = 0;
                    while (!csvParser.EndOfData && ile < end_time)
                    {
                        if (count >= start_time)
                        {
                            string[] f = csvParser.ReadFields();
                            user_data[i - 1].Add(new DataPoint(ile, double.Parse(f[i], System.Globalization.CultureInfo.InvariantCulture)));
                            ile += skok;
                        }
                        else
                        {
                            csvParser.ReadLine();
                            count += skok;
                        }
                    }

                }
            }
            List<DataPoint> pom1 = new List<DataPoint>();
            for (int i = fields.Count; i <= 8; i++)
            {
                user_data.Add(pom1);

            }
            if (wyw == 0)
            {
                for (int i = 0; i < data_list.Count; i++)
                {
                    fields_name[i] = data_list[i];
                }
                for (int i = data_list.Count; i < 8; i++)
                {
                    fields_name[i] = "";

                }
                Session["data_list"] = data_list;
            }
            else
            {
                var data = (List<String>)Session["data_list_2"];
                for (int i = 0; i < data.Count; i++)
                {
                    fields_name[i] = data[i];
                }
                for (int i = data.Count; i < 8; i++)
                {
                    fields_name[i] = "";
                }
                Session["data_list"] = data;
            }
            ViewBag.UserData1 = JsonConvert.SerializeObject(user_data[0]);
            ViewBag.UserData2 = JsonConvert.SerializeObject(user_data[1]);
            ViewBag.UserData3 = JsonConvert.SerializeObject(user_data[2]);
            ViewBag.UserData4 = JsonConvert.SerializeObject(user_data[3]);
            ViewBag.UserData5 = JsonConvert.SerializeObject(user_data[4]);
            ViewBag.UserData6 = JsonConvert.SerializeObject(user_data[5]);
            ViewBag.UserData7 = JsonConvert.SerializeObject(user_data[6]);
            ViewBag.UserData8 = JsonConvert.SerializeObject(user_data[7]);
            ViewBag.Fields1 = fields_name;
            return View();
        }

        public ActionResult Next_data()
        {
            int time = Convert.ToInt32(Session["start_time"]) + 30;
            Session["data_list_2"] = Session["data_list"];
            return RedirectToAction("User_plot", new { choose_Hz = Session["choose_Hz"], start_time = time, wyw = 1 });
        }
        public ActionResult Previous_data()
        {
            int time = Convert.ToInt32(Session["start_time"]) - 30;
            Session["data_list_2"] = Session["data_list"];
            return RedirectToAction("User_plot", new { choose_Hz = Session["choose_Hz"], start_time = time, wyw = 1 });
        }
    }
}

NET_projekt/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NET_projekt.Models;
using System.Text;
using System.Security.Cryptography;
using System.Web.UI.WebControls;
using Microsoft.VisualBasic.FileIO;
using Newtonsoft.Json;
using System.Net;
using System.IO;
using System.Data;

namespace NET_projekt.Controllers
{
    public class HomeController : Controller
    {
        private DefaultContext db = new DefaultContext();

        //HTTP: GET------------------------------------------------------------------
        public ActionResult Main_view()
        {
            string path = AppDomain.CurrentDomain.BaseDirectory;
            path = Path.Combine(Path.GetDirectoryName(Path.GetDirectoryName(path)), @"NET_projekt\");
            string[] filePaths = System.IO.Directory.GetFiles(path, "*.csv");
            foreach (string filePath in filePaths)

                System.IO.File.Delete(filePath);
            return View(new Example_Data());
        }
        [HttpPost]
        public ActionResult Main_view(HttpPostedFileBase file)
        {
            List<String> fields = new List<String>();
            if (Path.GetExtension(file.FileName) == ".csv")
            {
                ViewBag.Message_ok = "1";
                string path = Path.Combine(Server.MapPath("~"), Path.GetFileName(file.FileName));
                file.SaveAs(path);
                using (TextFieldParser csvParser = new TextFieldParser(path))
                {
                    csvParser.CommentTokens = new string[] { "#" };
                    csvParser.SetDelimiters(new string[] { "," });
                    csvParser.HasFieldsEnclosedInQuotes = true;
                    string[] f = csvParser.ReadFields();
                    fields = f.ToList();
                }
                ViewBag.Fields = fields;
                Session["fields"] = fields;
                Session["path"] = path;
                return View();
            }
            else if (Path.GetExtension(file.FileName) == ".dat")
            {
                string path = Path.Combine(Server.MapPath("~"), Path.GetFileName(file.FileName));
                file.SaveAs(path);
                Dat_to_Csv(path);
                System.IO.File.Delete(path);
                ViewBag.Message_ok = "1";
                path = Path.Combine(Path.GetDirectoryName(Path.GetDirectoryName(path)), @"NET_projekt\test.csv");
                file.SaveAs(path);
                using (TextFieldParser csvParser = new TextFieldParser(path))
                {
                    csvParser.CommentTokens = new string[] { "#" };
                    csvParser.SetDelimiters(new string[] { "," });
                    csvParser.HasFieldsEnclosedInQuotes = true;
                    string[] f = csvParser.ReadFields();
                    fields = f.ToList();
                }
                ViewBag.Fields = fields;
                Session["fields"] = fields;
                Session["path"] = path;
                return View();
            }
            else
            {
                ViewBag.Message_err = "Zły format pliku, wybierz plik csv lub dat ";
                return View();
            }


            return RedirectToAction("Main_view");

        }
        private static void Dat_to_Csv(string file)
        {
            System.Data.DataTable table = new System.Data.DataTable("dataFromFile");

            using (StreamReader sr = new StreamReader(file))
            {
                string line;
                while ((line = sr.ReadLine()) != null)
                {

                    string[] items = line.Trim().Split(',');
                    if (table.Columns.Count == 0)
                    {
                        for (int i = 0; i < items.Length; i++)
                            table.Columns.Add(new DataColumn("Column" + i, typeof(string)));
                    }
                    table.Rows.Add(items);
                }
            }

            string path = AppDomain.CurrentDomain.BaseDirectory;
            path = Path.Combine(Path.GetDirectoryName(Path.GetDirectoryName(path)), @"NET_projekt\test.csv");
            if (table != null && table.Rows.Count > 0)
            {
                StringBuilder data = new StringBuilder();
                for (int column = 0; column < table.Columns.Count; column++)
                {
                    if (column == table.Columns.Count - 1)
                        data.Append(table.Columns[column].ColumnName.ToString().Replace(",", ";"));
                    else
                        data.Append(table.Columns[column].ColumnName.ToString().Replace(",", ";") + ',');
                }

                data.Append(Environment.NewLine);

                for (int row = 0; row < table.Rows.Count; row++)
                {
                    for (int column = 0; column < table.Columns.Count; column++)
                    {
                        if (column == table.Columns.Count - 1)
                            data.Append(table.Rows[row][column].ToString().Replace(",", ";"));
                        else
                            data.Append(table.Rows[row][column].ToString().Replace(",", ";") + ',');
                    }
                    if (row != table.Rows.Count - 1)
                        data.Append(Environment.NewLine);
                }
                using (StreamWriter objWriter = new StreamWriter(path))
                {
                    objWriter.WriteLine(data);
                }
            }
        }
    }
}

NET_projekt/Views/Home/AddDataset.cshtml
@model NET_projekt.Models.Dataset

@{
    ViewBag.Title = "Add Dataset";
}
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<link href="~/Content/Site.css" rel="stylesheet" />

@using (Html.BeginForm("AddDataset", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <h4>Dodawanie dataset'u</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label for="file">Załącz plik (.csv):</label>
            <input type="file" name="file" id="file" />
            <div style="color: red;">
                @ViewBag.Message
            </div>
        </div>

        <div class="form-group" style="margin-top:20px;">
            @Html.LabelFor(m => m.DatasetName)
            <div>
                @Html.EditorFor(m => m.DatasetName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.DatasetName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.DatasetColumnsInfo)
            <div>
                @Html.EditorFor(m => m.DatasetColumnsInfo, new { htmlAttributes = new { @class = "form-control" } })
                @if (ViewBag.dataseterror != null)
                {
                    <span class="badge badge-danger">@ViewBag.dataseterror</span>
                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.DatasetHzFrequency)
            <div>
                @Html.EditorFor(m => m.DatasetHzFrequency, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.DatasetHzFrequency, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group" , style="margin-top:20px;">
            <input type="submit" class="btn btn-success" value="Dodaj dataset" /> |
            @Html.ActionLink("Powrót", "Index")
        </div>

    </div>
}

NET_projekt/Views/Home/DeleteDataset.cshtml
@model NET_projekt.Models.Dataset

@{
    ViewBag.Title = "Delete Dataset";
}

<h3>Jesteś pewien usunięcia wybranego dataset'u?</h3>
<h4>Operacja ta jest nieodwracalna.</h4>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(m => m.DatasetName):
        </dt>
        <dd>
            @Html.DisplayFor(m => m.DatasetName)
        </dd>
        <dt>
            @Html.DisplayNameFor(m => m.DateAdded):
        </dt>
        <dd>
            @Html.DisplayFor(m => m.DateAdded)
        </dd>
        <dt>
            @Html.DisplayNameFor(m => m.DatasetHzFrequency):
        </dt>
        <dd>
            @Html.DisplayFor(m => m.DatasetHzFrequency) [Hz]
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" class="btn btn-danger" value="Usuń"/> |
            @Html.ActionLink("Powrót", "Index")
        </div>
    }
</div>

NET_projekt/Views/Home/Graph.cshtml
@model NET_projekt.Models.GraphModel
@{
    ViewBag.Title = "Graph";
}

<!DOCTYPE HTML>
<html>
<head>
    <script>
        var freq = @Convert.ToString(Model.Dataset.DatasetHzFrequency);
        var l = "@Html.Raw(Model.Dataset.DatasetColumnsInfo)";
        var time = "@Html.Raw(Model.Time)";
        l = l.split(" ");
        for (var i = 0; i < l.length; i++) {
            l[i] = l[i].split(":");
            l[i][1] = l[i][1].split(",");
        }
        var typeList = new Array(l.length);
        for (var i = 0; i < typeList.length; i++) {
            typeList[i] = l[i][0];
        }
        var l2 = new Array();
        for (var i = 0; i < l.length; i++) {
            l2.push(l[i][1]);
        }
        var newlist = prepCols(l2);
        function prepCols(lst) {
            //prepare empty list
            var lst2 = new Array(lst.length);
            for (var i = 0; i < lst2.length; i++) {
                lst2[i] = new Array(lst[i].length)
                for (var j = 0; j < lst2[i].length; j++) {
                    lst2[i][j] = { name: typeList[i] + " sensor " + (j + 1), type: "line", showInLegend: true, dataPoints: [] };
                }
            }
            //fill list
            var splitedLines = @Html.Raw(ViewBag.DataLines);
            for (var executedColumns = 0; executedColumns < splitedLines.length; executedColumns++) {
                var s = splitedLines[executedColumns].split(",");
                //document.write("<br>" + splitedLines[executedColumns] + "</br>");
                for (var i = 0; i < lst.length; i++) {
                    for (var j = 0; j < lst[i].length; j++) {
                        lst2[i][j]['dataPoints'].push({ x: (parseInt(time) + executedColumns/freq), y: parseFloat(s[lst[i][j]]) });
                    }
                }
            }
            return lst2;
        }

        window.onload = function () {
            var charts = new Array(typeList.length);
            for (var i = 0; i < typeList.length; i++) {
                charts[i] = new CanvasJS.Chart("chart" + String(i),
                    {
                        animationEnabled: true,
                        title: {
                            text: "Wykres dla danych " + typeList[i]
                        },
                        axisX: {
                            title: "Czas [s]",
                            interval: 1,
                            suffix: "s"
                        },
                        axisY: {
                            title: "Aplituda Sygnału [mV]"
                        },
                        legend: {
                            cursor: "pointer",
                            fontSize: 16,
                            itemclick: toggleDataSeries
                        },
                        toolTip: {
                            shared: true
                        },
                        data: newlist[i]
                    });
            }
            for (var i = 0; i < charts.length; i++) {
                charts[i].render();
            }
        }

        function toggleDataSeries(e) {
            if (typeof (e.dataSeries.visible) === "undefined" || e.dataSeries.visible) {
                e.dataSeries.visible = false;
            }
            else {
                e.dataSeries.visible = true;
            }
            e.chart.render();
        }
    </script>
</head>
<body>
    <script>
        for (var i = 0; i < typeList.length; i++) {
            var x = "<div id=chart" + i + " style=\"height: 370px; width: 100 %;\"></div>";
            document.write(x);
        }
    </script>
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>

    <div style="margin-top:20px;">
        <div class=" text-center">
            <input type="button" class="btn btn-dark" value="Poprzednie dane" onclick="location.href='@Url.Action("Graph", "Home", new { Id = Model.Dataset.Id, time = Model.Time - 30, previousData=true })'" />
            <input type="button" class="btn btn-dark" value="Następne dane" onclick="location.href='@Url.Action("Graph", "Home", new { Id = Model.Dataset.Id, time = Model.Time + 30 })'" />
        </div>
    </div>
    <div style="margin-top:10px;">
        <div class=" text-center">
            @using (Html.BeginForm("Graph", "Home", FormMethod.Get))
            {
                <input type="submit" class="btn btn-dark" value="Skocz do sekundy" />
                @Html.TextBoxFor(m => m.Time)
            }
        </div>
    </div>
    <div style="margin-top:10px;">
        <div class=" text-center">
            <input type="button" class="btn btn-dark" value="Wróć" onclick="location.href='@Url.Action("Index", "Home")'" />
        </div>
    </div>
</body>
</html>

NET_projekt/Views/Home/Index.cshtml
@model NET_projekt.Models.User

@{
    ViewBag.Title = "Index";
}
<div class="row justify-content-md-end">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                Witaj
            </div>
            <div class="card-body">
                @if (Session["UserId"] != null)
                {
                    <p>Nazwa: @Session["Nickname"].ToString()</p>
                    <p>E-mail: @Session["EmailAddress"].ToString()</p>
                    <a href="@Url.Action("Logout","Home")" class="btn btn-dark">Wyloguj się</a>
                }
            </div>
        </div>
    </div>
</div>

<div style="margin-top: 50px;"><h1 class="row justify-content-md-center">Dostępne dataset'y:</h1></div>
<table class="table">
    <caption>Dataset'y użytkownika @Session["Nickname"].ToString()</caption>
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nazwa dataset'u</th>
            <th scope="col">Data dodania</th>
            <th scope="col">Typy danych</th>
            <th scope="col">Częstotliwość [Hz]</th>
            <th scope="col" class="text-center">Podgląd</th>
        </tr>
    </thead>
    <tbody>
        @{
            for (int i = 0; i < Model.Datasets.Count; i++)
            {
                <tr>
                    <th scope="row">@i</th>
                    <td>@Html.DisplayFor(modelItem => Model.Datasets.ElementAt(i).DatasetName)</td>
                    <td>@Html.DisplayFor(modelItem => Model.Datasets.ElementAt(i).DateAdded)</td>
                    <td>@{
                        string types = "";
                        foreach(var item in Model.Datasets.ElementAt(i).DatasetColumnsInfo.Split(' '))
                        {
                            types += item.Split(':')[0]+" ";
                        }
                        @types
                        }</td>
                    <td>@Html.DisplayFor(modelItem => (Model.Datasets.ElementAt(i).DatasetHzFrequency))</td>
                    <td class="text-center">
                        <input type="button" value="Przejrzyj" class="btn btn-success" onclick="location.href='@Url.Action("Graph", "Home", new { id = Model.Datasets.ElementAt(i).Id })'" />
                        <input type="button" value="Usuń" class="btn btn-danger" onclick="location.href='@Url.Action("DeleteDataset", "Home", new { id = Model.Datasets.ElementAt(i).Id })'" />
                    </td>
                </tr>
            }
        }
    <tr>
        <td colspan="5"></td>
        <td class="text-center"><input type="button" value="Dodaj nowy" class="btn btn-primary" onclick="location.href='@Url.Action("AddDataset", "Home", new { UserId = Model.UserId  })'"/></td>
    </tr>
    </tbody>
</table>

NET_projekt/Views/Home/Login.cshtml
@model NET_projekt.Models.User

@{
    ViewBag.Title = "Login";
}

<div class="row justify-content-md-center">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Logowanie</div>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Login", "Home", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                <div class="form-group">
                    @Html.LabelFor(m => m.Nickname)
                    @Html.TextBoxFor(m => m.Nickname, "", new { @class = "form-control", @placeholder = "Nazwa użytkownika" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password)
                    @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Hasło" })
                    @if (ViewBag.error != null)
                    {
                        <span class="badge badge-danger">@ViewBag.error</span>
                    }
                </div>
                    <div class="form-group">
                        <input type="submit" name="submit" class="btn btn-primary" value="Login" />
                    </div>
                }
                @Html.ActionLink("Nie masz konta? Zarejestruj się.", "Register")
            </div>
        </div>
    </div>
</div>

NET_projekt/Views/Home/Main_view.cshtml
@using NET_projekt.Models
@model NET_projekt.Models.Example_Data

@{
    ViewBag.Title = "Main_view";
}

<div class="container">
    <div class="row justify-content-evenly">
        <div class="col-4">
            <div class="fs-3">
                Wizualizacja danych bez logowania
                <div class="text-center"> <span> &nbsp; &nbsp;</span> </div>
            </div>

            @using (Html.BeginForm("Main_view", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
        <div>
            @Html.TextBox("file", "", new { type = "file" }) <br />
            <div class= "text-center"> <span> &nbsp; &nbsp; </span> </div>
            <input type="submit" value="Przeslij" , class="btn btn-light" />
            @if (ViewBag.Message_err != null)
            {
                <span class="badge badge-danger">@ViewBag.Message_err</span>
            }
        </div>
            }

            @using (Html.BeginForm("User_plot", "ExamplePlot", FormMethod.Post, new { enctype = "multipart/form-data"}))
            {

                if (ViewBag.Message_ok == "1")
                {
        <div>


            @foreach (string s in @ViewBag.Fields)
            {
                if (s != "")
                {
                    @Html.TextBoxFor(m => m.data_list, "")
                    <label class="label label-default">@s</label>
                    <div>

                    </div>

                }
            }
            @Html.TextBoxFor(m => m.choose_Hz)
            <label class="label label-default">Częstotoliwość w HZ</label>
            @Html.Hidden("start_time", 0)
            @Html.Hidden("wyw", 0)
            <input type="submit" value="Generuj wykresy", class="btn btn-light" />
        </div>
                }
            }
            </div>
        
        <div class="col-4">

            @using (Html.BeginForm("Example_plot", "ExamplePlot", new { id = "FilterClick" }, FormMethod.Post, null))
            {
            <div class=" text-center">
                <div class="row justify-content-center">
                    <div class="fs-3">
                        Wizualizacja przykładowych danych
                        <div class="text-center"> <span> &nbsp; &nbsp;</span> </div>
                    </div>
                    <div class="col-4">
                        <div class="form-check">

                            @Html.CheckBoxFor(m => m.ecg)
                            <label class="form-check-label" for="ecg">ECG</label>

                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-check">
                            @Html.CheckBoxFor(m => m.emg)
                            <label class="form-check-label" for="emg" , value="1">EMG</label>
                        </div>
                    </div>
                </div>
                <div class="text-center"> <span> &nbsp; &nbsp;</span> </div>
                @Html.DropDownListFor(m => m.choose_Hz,
                                                       new List<SelectListItem> {
                                                             new SelectListItem { Value = "10", Text = "10Hz" },
                                                             new SelectListItem { Value = "100", Text = "100Hz" },
                                                             new SelectListItem { Value = "250", Text = "250Hz" }
                                                       }, "Wybierz czestotliwośc")

                @Html.DropDownListFor(m => m.time,
                                                        new List<SelectListItem> {
                                                              new SelectListItem { Value = "10", Text = "10s" },
                                                              new SelectListItem { Value = "20", Text = "20s" },
                                                              new SelectListItem { Value = "30", Text = "30s" }
                                                        }, "Wybierz czas")
                <div class="text-center">
                    <span> &nbsp; &nbsp; &nbsp;</span>
                </div>
                <div class="text-center"> <input type="submit" value="Generuj wykres" id="Submit" class="btn btn-light" /> </div>

            </div>
            }
        </div>

    </div>
</div>

NET_projekt/Views/Home/Register.cshtml
@model NET_projekt.Models.User

@{
    ViewBag.Title = "Register";
}

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<link href="~/Content/Site.css" rel="stylesheet" />

<div class="row justify-content-md-center">
    <div class="col-md-5">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Rejestracja</div>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Register", "Home", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        @Html.LabelFor(m => m.Nickname)
                        @Html.TextBoxFor(m => m.Nickname, "", new { @class = "form-control", @placeholder = "Nazwa użytkownika" })
                        @Html.ValidationMessageFor(m => m.Nickname, "", new { @class = "badge badge-danger" })
                        @if (ViewBag.error != null)
                        {
                            <span class="badge badge-danger">@ViewBag.error</span>
                        }
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.EmailAddress)
                        @Html.TextBoxFor(m => m.EmailAddress, "", new { @class = "form-control", @placeholder = "Adres e-mail" })
                        @Html.ValidationMessageFor(m => m.EmailAddress, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Password)
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Hasło" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        <input type="submit" name="submit" class="btn btn-danger" value="Rejestracja" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>